version: '3'

services:
  tradingbot:
    volumes: ./config.js:/usr/src/app/config.js

  mongod:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017

